### PR TITLE
Adding @conspiracy_r to "In The Wild" section

### PR DESCRIPTION
**Pull request by tonyravioli**

### CODE REVIEW

**Comment by jsvine** [comment]
Thank you for the suggestion. Do you happen to have a link to the code used for this example?

**Comment by tonyravioli** [comment]
I don't have it hosted on Github (yet(?)), but here's the code:

```
#!/usr/bin/env python3
import tweepy
import markovify.text

ckey = "[redacted]"
csecret = "[redacted]"

akey = "[redacted]"
asecret = "[redacted]"

auth = tweepy.OAuthHandler(ckey, csecret)
auth.set_access_token(akey, asecret)

api = tweepy.API(auth)


logfile = "../../conspiradump.txt"
with open(logfile) as f:
    text = f.read()
model = markovify.text.NewlineText(text, state_size=3)

def go(sentences=2):
    longstring = ''

    for i in range(sentences):
        try:
            sentence = model.make_sentence(tries=20).strip()
            if sentence.endswith("." or "?"):
                longstring += "{} ".format(sentence)
            else:
                longstring += "{}, ".format(sentence)
        except AttributeError:
            continue
    if longstring.strip().endswith(','):
        return '{}.'.format(longstring.strip()[:-1])
    else:
        return longstring.strip()

generated = go()
while len(generated) > 279:
  generated = go()
  print('too long')

while generated.endswith(('?','.')):
  generated = generated[:-1]
generated = generated.replace('?.','?')
generated = generated.replace('!.','!')

print(generated)
api.update_status(generated)
```

If you need me to host this on Github, I can do that.

**Comment by jsvine** [comment]
If you could, that'd be helpful, so that other `markovify` users can learn from the example. Thanks!

**Comment by jsvine** [comment]
Closing this PR for lack of activity, but feel free to reopen if you end up hosting the code on GitHub (or elsewhere).

**Pull request closed without merging**
