### PR TITLE
allow for a sentence that starts with words even of those words don't…

### PR DESCRIPTION
**Pull request by danmayer**
… start any sentence in the corpus

This adds a feature I would like which is also in this open issue: https://github.com/jsvine/markovify/issues/48

basically this would allow one to start sentences with words that exist in the corpus but never previously started sentences. 

I apologize for any odd style or formatting. I am not really a python programmer, but more Ruby, etc... If you want any style changes let me know or feel free to modify what I sent.

### CODE REVIEW

**Comment by danmayer** [comment]
resolved coverage should be back at 100%

**Comment by jsvine** [comment]
I'm glad you decided to take a crack at this! It seems to me, though, that this approach doesn't preserve word-order in multi-word inputs. For instance, if I have a model with `state_size=3`, and I run `.make_sentence_with_words("quantum mechanics")`, I would (in theory) receive sentences that included both `"quantum mechanics"` and `"mechanics quantum"`. Is that correct? (Maybe I'm just mistaken?) And is that intended?

These are the lines that makes me think of the above:

```python
def isSubSet(self, superset = [], subset = []):
    return all(x in superset for x in subset) and len(subset)>0

# [...]

possibleKeys = [key for key in self.model.keys() if self.isSubSet(key,state)]
```

**Comment by danmayer** [comment]
hmm I think you are correct. I will add a test case and prove out for multi-word. My use case only required one word so I hadn't thought as deeply. I should be able to whip up a solution over the weekend.

**Comment by danmayer** [comment]
OK, take a look @jsvine while I think this is probably pretty slow on large corpuses, but given it only enters this method until it reaches initial state. I think that is acceptable. This seems to cover my use cases and the test cases I came up with. If you have any other test examples I should add let me know.

**Comment by jsvine** [comment]
Thanks, @danmayer! I think this is getting closer. A few remaining issues:

- The call to `possibleKeys` is currently placed in a `elif` block within `self.move`. But `self.move` is invoked every single time `markovify` searches for the next state, while the generation of possible keys is only required once per sentence, at the very beginning of the sentence-generation process. I think the call to `possibleKeys` would fit more cleanly and efficiently inside `self.make_sentence_with_words`. What do you think?

- Given what it does, `isOrderedSubset` would seem more properly to be a function in the submodule's global scope, rather than a method of `Chain`.

- I'm a bit wary of using `"_".join` in the `isOrderedSubset`, and more generally string-joining lists to test the subsets. What about something like this?:

```python
def list_is_in_list(sub_list, super_list):
    # Stop immediately if super_list is missing any of sub_list's items
    if len(set(sub_list) - set(super_list)) > 0:
        return False

    # Iterate through sub_list-length slices of super_list
    sub_len = len(sub_list)
    for i in range(1 + len(super_list) - sub_len):
        if super_list[i:i+sub_len] == sub_list:
            return True

    return False
```

**Comment by danmayer** [comment]
ok taking a look current issue is that `list_is_in_list`, but I think I can figure something out.

returns possible keys like so:

`[('accustomed', 'was', 'I'), ('was', 'I', 'to'), ('it', 'was', 'I'), ('was', 'I', 'gave')]`

which has both "* was I" and "was I *" cases, where as the string version only returns:

`[('was', 'I', 'to'), ('was', 'I', 'gave')]`

which means we always start with and never end with the expected keys... the other can lead to attempting to generate a chain that has no matches resulting in a `KeyError`

**Comment by danmayer** [comment]
OK resolved ok resolved that issue and was able to reduce to something much cleaner... looking at other comments again.

**Comment by danmayer** [comment]
OK refactoring out of move was a bit harder than I guessed because the random retries were actually resolving a case where of only two possible paths form "was I" which I used in testing, one path always fails because of it being too similar with too much overlap... Once I realized that was the issue, I have it try from a random order of possible initial states until it finds a successful run.

I think this should be pretty good now @jsvine

**Comment by jsvine** [comment]
Thanks, Dan! I think we're nearly there. (And good point about the `list_is_in_list` method choosing undesirable keys.) A few remaining questions / suggestions:

- Is there a particular reason this PR includes `import pdb`?

- I think the current logic is skipping beginning-of-sentence keys that it would actually like to accept, e.g., `(BEGIN, "I", "hear")` for the desired sentence-start of `"I hear"`. Or am I misreading that?

- I think `is_ordered_subset` isn't quite the correct nomenclature, since you're looking for something more specific than an ordered subset. I think, though, you can actually forget about the nomenclature question entirely by removing the two new `Chain` methods and moving that logic into your `make_sentence_with_words`. I.e.,:

```python
import random
# ...
# ...
# ...

    def make_sentence_with_words(self, beginning, **kwargs):
        """
        Tries making a sentence that contains the `beginning` string,
        which should be a string of one or two words known to exist in the
        corpus. Similar to make_sentence_with_start, but doesn't require
        word to start the sentence.**kwargs are passed to `self.make_sentence`.
        """
        split = tuple(self.word_split(beginning))
        word_count = len(split)

        if (word_count > 0 and word_count < self.state_size):

            possible_keys = [ key for key in self.chain.model.keys()
                # Line below handles issue mentioned above
                if tuple(filter(lambda x: x != BEGIN, key))[:word_count] == split ]
            random.shuffle(possible_keys)

            for possible_state in possible_keys:
                output = self.make_sentence(possible_state, **kwargs)
                if output is not None:
                    return output
            return None

        elif word_count == self.state_size:
            init_state = split

        else:
            err_msg = "`make_sentence_with_words` for this model requires a string containing 1 to {0} words. Yours has {1}: {2}".format(self.state_size, word_count, str(split))
            raise ParamError(err_msg)
        return self.make_sentence(init_state, **kwargs)
```

... What do you think?

- And speaking of nomenclature, "`make_sentence_with_words`" seems slightly off, since (a) order matters, (b) you want the sentence to start with those words, and (c) the method is expecting a single `str`, rather than a tuple of words. In fact, it's a lot like `make_sentence_with_start`, but with a slightly different rule about what initial keys to consider. So what would you think about rolling this logic into the pre-existing `make_sentence_with_start` method, and triggering it with a keyword flag, e.g., `make_sentence_with_start("I hear", strict=False)`? (Open to other flag names!) If that approach works for you, I can merge your PR and then make that change.

**Comment by danmayer** [comment]
All sounds good, I removed the `import pdb` I left that while debugging... I refactored as you suggest and merging with the other method makes sense to me. Thanks, I feel this turned out much cleaner than the initial approach.

**Comment by jsvine** [comment]
Great! I have now:

- squash-merged your PR
- merged with `make_sentence_with_start`
- updated `make_sentence_with_start`'s docstring to explain the new `strict=` keyword argument
- tweaked the new tests to work with `make_sentence_with_start`
- thanked you in the README. (Thank you, indeed!)
- bumped the version to `0.7.0`
- pushed the new version to PyPi

**Comment by danmayer** [comment]
excellent thanks @jsvine happy to see this go live!

**Pull request merged**
