### PR TITLE
removes exceptions from splitters

### PR DESCRIPTION
**Pull request by asdqwex**
Not sure why that is in there but it looks like it is unneeded. Feel free to merge or reject as you see fit.

### CODE REVIEW

**Comment by jsvine** [comment]
Thanks @asdqwex! If I recall correctly — and it's been a while since I wrote those lines — the exceptions are meant to keep certain period-separated abbreviations stuck together, e.g., so "C.I.A." remains "C.I.A." and not three sentences ("C", "I", "A"). Ideally, markovify would have a more complete list of these abbreviations ... *or* a more sophisticated/generalized approach to detecting non-sentence-ending-periods. What do you think?

**Comment by alpha-beta-soup** [comment]
Shouldn't it just consider any letter/s-separated-by-periods as acronyms, and not break them? U.S.A. and USA are semantically the same thing. I can't think of many cases where any period that is not followed by a whitespace character is sentence-ending. You just have to be careful to note that not all acronyms are `\b(?:[a-zA-Z]*\.){2,}`, but also `\b(?:(?:[a-zA-Z])*\.){2,}` (the latter matches `Ph.D` whereas the former does not).

**Comment by jsvine** [comment]
That sounds like a promising approach. Thank you for suggesting it.

**Comment by jsvine** [comment]
Very belatedly, thank you for the suggestion. v0.8.3 now checks for a generic pattern, rather than a preformed list.

**Pull request closed without merging**
