### PR TITLE
Modernize the code to Python 3.6+

### PR DESCRIPTION
**Pull request by eumiro**
Now that we're at Python 3.6+, we can modernize the code and add f-strings, `pathlib.Path` and other Python3 features.

Next steps would be to convert the tests to `pytest`. What do you think?

### CODE REVIEW

**Comment by jsvine** [comment]
Thanks! On the whole, I like the ideas here. But this PR introduces a lot of line-changes, spanning a few different suggestions, so it'll take me a little while to audit it. (I realize that many of the changes are auto-generated, but I'd still like to read them carefully.)

**Comment by eumiro** [comment]
Sorry for that huge diff. Would you like me to split different topics better into individual commits? That's a big change, but while the best moment to set formatting standards was at the beginning of the project, the second best is now.

**Comment by jsvine** [comment]
I think it's fine to keep this PR as-is, but thanks for offering.. I haven't forgotten about the PR, but have been busy. I hope to take a closer look soon.

**Comment by jsvine** [comment]
Thanks again, @eumiro. I've taken some of these ideas, and some of the commits directly, and incorporated them into #166, now merged. 

One thing I didn't do was to use `pathlib`; it's a good idea, but does not play a major role here. If you'd like, feel free to submit a PR specifically for that.

**Pull request closed without merging**
