### PR TITLE
support a compiled chain.model for improved performance

### PR DESCRIPTION
**Pull request by erikerlandson**
This PR proposes to add a new compiled format for `chain.model` that  pre-caches all the state transitions, as opposed to caching only the "begin".

I've been seeing generation 50 to 100x faster.  Generation throughput increase depends on model size.

### CODE REVIEW

**Comment by jsvine** [comment]
Thank you, @erikerlandson! This sounds both interesting and likely worth merging. I'll aim to take a closer look soon. 

In the meantime, would you be willing to add a short description to the notes section [here](https://github.com/jsvine/markovify/blob/master/README.md#basic-usage), right after the bullet point that begins "If you have accidentally read [...]"?

**Comment by erikerlandson** [comment]
@jsvine it is done :+1:

**Comment by erikerlandson** [comment]
@jsvine have you had a chance to look at this?

**Comment by jsvine** [comment]
HI @erikerlandson, and thank you for the reminder! Now that I've had the chance to look at the code, I have a question about the implementation: Why not make `CompiledText` a subclass of `Text`? My concern is that many of the methods in `CompiledText` are simply `Text` methods. Ideally, when fixes or features come to the `Text` method, `CompiledText` would  be able to automatically receive those, too, as a subclass (rather than having to manually keep `CompiledText`'s features/fixes in sync with `Text`'s. Or did you already consider subclassing and dismiss it as suboptimal?

**Comment by erikerlandson** [comment]
@jsvine, sorry I didn't see your comment :frowning:   My original reasoning about not making it a subclass is that not all `Text` methods are good fits for `CompiledText`.  For example, actually training a `CompiledText` object directly is possible but I think better with traditional `Text`.  Another operation I had in mind was `combine`, however that isn't actually defined on `Text` so it's not the problem I assumed.

If we can design it so that a sufficient number of methods are directly inherited, and the  overloadings that need to be maintained are relatively stable, then I think it would be a good idea.

**Comment by erikerlandson** [comment]
@jsvine another possible strategy would be to define something like a `TextBase` that defines some common core API, and have both `Text` and `CompiledText` inherit from that.

**Comment by jsvine** [comment]
Thanks for the response, @erikerlandson! My thoughts below. 

> If we can design it so that a sufficient number of methods are directly inherited, and the overloadings that need to be maintained are relatively stable, then I think it would be a good idea.

Fantastic! I think you're right that some of the traditional `Text` methods might not make sense for `CompiledText`, and I think that's fine. For those, I think it's reasonable to raise a `NotImplemented` error, or something similar.

> another possible strategy would be to define something like a TextBase that defines some common core API, and have both Text and CompiledText inherit from that.

Interesting! In the abstract, I can see how that might be useful. If you want to propose a rough (non-code) outline for how `TextBase` would differ from the current `Text` class, I'd certainly take a look. I'll also ruminate on this.

**Comment by erikerlandson** [comment]
@jsvine, it occurs to me that what is really being "compiled" is just the `Chain` object.  Looking at the organization of `Text`, I am now thinking it would be most elegant to have a `CompiledChain` class, and modify a few of the core methods to do the right thing with either `Chain` or `CompiledChain`.

something like `combine` could just fail if it encounters a `CompiledChain` (and if someone feels motivated in the future, `combine` could augmented to support it, but I'm treating it as out of scope for this PR)

Doing it this way should also handle `to_json` and friends, and also `test_sentence_output` - if (like me) one also wants to avoid the cost of keeping the original text around, then that is already supported on `Text`.

**Comment by erikerlandson** [comment]
In fact, it's just the `chain.model` - I may try just adding a flag to encode whether `model` is compiled or not. `Text` might not need to be modified at all.

**Comment by jsvine** [comment]
That sounds like a smart, promising approach!

**Comment by erikerlandson** [comment]
I'll try to get to it soon, it's been a hectic couple of weeks :D

**Comment by erikerlandson** [comment]
@jsvine what do you think of this?

**Comment by jsvine** [comment]
Thanks, @erikerlandson! I'm impressed by how concise you were able to make the changes. I'll need a bit more time to think through this and review it more carefully, but on first glance it looks promising.

One question that initially comes to mind: Is it a better experience for users to have `.compile(...)` make in-place modifications, or should it return a new instance without modifying the original? (Off the top of my head, I believe that no other `Model` methods produce in-place changes; the class is, at least superficially, immutable.)

**Comment by erikerlandson** [comment]
@jsvine, I have no problem making it return a copy.  I could support an `in_place = False` parameter, that would allow someone to compile it in-place if desired, but default to returning a new `Text` model

**Comment by erikerlandson** [comment]
@jsvine here's a tweak that makes non-destructive compile the default

**Comment by jsvine** [comment]
Many thanks @erikerlandson! These changes look great. Merged, and now available in `v0.8.0`. Cheers!

**Pull request merged**
